
import React from 'react';
import { DM_Sans } from "next/font/google";
import "./globals.css";
import "@rainbow-me/rainbowkit/styles.css";
import { Metadata } from 'next';
import dynamic from 'next/dynamic';
import Navbar from './Components/Navbar';


const dm_sans = DM_Sans({
  weight: ["400", "600", "700"],
  style: ["normal"],
  subsets: ["latin"],
  variable: "--font-dmsans",
  display: "swap",
});

interface RootLayoutProps {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const Providers = dynamic(() => import("@/app/provider"), { ssr: false })

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className={dm_sans.variable}>
      <head>
        <title></title>
      </head>
      <body>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}